### ISSUE TITLE
256 is not between 0 and 255

### ISSUE THREAD

**Issue by anneetien** [badetitou/SmartTest#24]
- Take a new version of Moose 6.1
- Install SmartTest
- Configure SmartTest to get the big button, not Renraku, and Reflexivity to find the tests. 
- Modify MooseEntity>>children to add for example self halt at the beginning and save.
- All the tests are run to dynamically find the one impacted by the change (quite long by the way).
- An error in Opal occurs because 256 is not range between 0 and 255. I don't know if it is a problem in one test, to display the result in the big button or something else but an error occurs.

**Comment by badetitou** [comment]
Please go to 
System>Settings>Compiler>Bytecode Backend>SistaV1.
And the problem should be solve after recompiling all the methods
