### ISSUE TITLE
Inheritance in Test

### ISSUE THREAD

**Issue by anneetien** [badetitou/SmartTest#25]
- Take a new version of Moose 6.1
- Install SmartTest
- Configure SmartTest to get the big button, not Renraku, and for the reminder, let the values by default.
- before doing any change, run all the tests of Moose, Famix and Fame with the testrunner
- Modify MooseEntity>>children to add for example self halt at the beginning and save.
- After a long delay, 11 is displayed in the big button that is gray. 
- Click on it and it becomes red with 36 displayed whereas no more change has been done.
- The tests are red because whereas they inherit from an abstract test class and override the abstract method.
- run with the testrunner the same test than before the change, they are all green.

And by the way 11 became 36 just like that, very strange.

**Comment by badetitou** [comment]
The bug should be solved with the last version
