### ISSUE TITLE
Tool long notification message

### ISSUE THREAD

**Issue by JurajKubelka** [badetitou/SmartTest#34]
Hi,

I recommend to make a smarter notification about method execution. In my case, there were too many executed test cases and the notification was too big. 

There is a proposal that can be improved:

```Smalltalk
notifyTitle: title contents: aTestResult

	| contents |
	contents := aTestResult tests size > 3
		ifTrue: [ String streamContents: [ :aStream | 
				aStream 
					<< aTestResult tests size
					<< ' tests in: '.
				(aTestResult tests collect: #class as: Set) 
					do: [ :eachClass | aStream << eachClass name ]
					separatedBy: [ aStream << ', ' ] ] ]
		ifFalse: [ aTestResult  ].

	 GrowlMorph 
		openWithLabel: title
		contents: contents
		backgroundColor: (self colorForTestResultOf: aTestResult )
		labelColor: Color black
```

BTW, I had to switch off the plugin. For some reason, maybe because I downloaded another project after, the image got unresponsive, moving windows was too slow, and test cases were executed without the need to modify the code.

**Comment by badetitou** [comment]
Hi,

OK. I'll try to do this improvement.
At the same time i'll look for this strange bug ... If you can reproduce it, tell me.

**Comment by badetitou** [comment]
Update done in last dev version. Will come soon in the stable version
